In [2]:
pip install yfinance

Requirement already satisfied: yfinance in f:\anaconda\lib\site-packages (0.1.74)
Requirement already satisfied: pandas>=0.24.0 in f:\anaconda\lib\site-packages (from yfinance) (1.3.4)
Requirement already satisfied: multitasking>=0.0.7 in f:\anaconda\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: numpy>=1.15 in f:\anaconda\lib\site-packages (from yfinance) (1.20.3)
Requirement already satisfied: requests>=2.26 in f:\anaconda\lib\site-packages (from yfinance) (2.26.0)
Requirement already satisfied: lxml>=4.5.1 in f:\anaconda\lib\site-packages (from yfinance) (4.6.3)
Requirement already satisfied: pytz>=2017.3 in f:\anaconda\lib\site-packages (from pandas>=0.24.0->yfinance) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in f:\anaconda\lib\site-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in f:\anaconda\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in f:\anaconda\lib\site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in f:\anaconda\lib\site-packages (from requests>=2.26->yfinance) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in f:\anaconda\lib\site-packages (from requests>=2.26->yfinance) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\anaconda\lib\site-packages (from requests>=2.26->yfinance) (1.26.7)
Note: you may need to restart the kernel to use updated packages.

In [12]:
from statsmodels.tsa.stattools import adfuller

In [3]:
import yfinance as yf
import pandas as pd

In [39]:
msft = yf.Ticker("MSFT")

In [40]:
df = pd.DataFrame(msft.history())

In [41]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-08-23,276.440002,278.859985,275.399994,276.440002,17527400,0,0
2022-08-24,275.410004,277.230011,275.109985,275.790009,18137000,0,0
2022-08-25,277.329987,279.019989,274.519989,278.850006,16583400,0,0
2022-08-26,279.079987,280.339996,267.980011,268.089996,27549300,0,0
2022-08-29,265.850006,267.399994,263.850006,265.230011,20338500,0,0
2022-08-30,266.670013,267.049988,260.660004,262.970001,22767100,0,0
2022-08-31,265.390015,267.109985,261.329987,261.470001,24791800,0,0
2022-09-01,258.869995,260.890015,255.410004,260.399994,23263400,0,0
2022-09-02,261.700012,264.739990,254.470001,256.059998,22841600,0,0
2022-09-06,256.200012,257.829987,251.940002,253.250000,21328200,0,0
2022-09-07,254.699997,258.829987,253.220001,258.089996,24126700,0,0
2022-09-08,257.510010,260.429993,254.789993,258.519989,20319900,0,0
2022-09-09,260.500000,265.230011,260.290009,264.459991,22084700,0,0
2022-09-12,265.779999,267.450012,265.160004,266.649994,18747700,0,0
2022-09-13,258.839996,260.399994,251.589996,251.990005,33353300,0,0
2022-09-14,253.529999,254.229996,249.860001,252.220001,23913000,0,0
2022-09-15,249.770004,251.399994,244.020004,245.380005,31530900,0,0
2022-09-16,244.259995,245.300003,242.059998,244.740005,39775100,0,0
2022-09-19,242.470001,245.139999,240.850006,244.520004,26826900,0,0
2022-09-20,242.070007,243.509995,239.639999,242.449997,26660300,0,0
2022-09-21,244.270004,247.660004,238.899994,238.949997,28625600,0,0
2022-09-22,237.870407,243.860001,237.570007,240.979996,30177240,0,0

In [18]:
chuppe = []

In [13]:
print(len(df))

23

In [27]:
for i in range (len(df)):
    chuppe.append(((df["Close"][i]-df["Open"][i])/df["Open"][i]))

In [28]:
chuppe

[-0.015350208374872894,
 0.0,
 0.0013797787943778336,
 0.005480905797591848,
 -0.03937935632489084,
 -0.0023321237651056843,
 -0.013874871641816324,
 -0.014770764578038937,
 0.005910297864394296,
 -0.021551449695675507,
 -0.011514488940177687,
 0.013309773970422632,
 0.003922097043785274,
 0.015201502706633877,
 0.0032733656452077196,
 -0.02646419000788642,
 -0.005167031770998153,
 -0.01757616733216539,
 0.001965164157549718,
 0.008454666727583514,
 0.0015697509502467805,
 -0.02177920838075872,
 0.022657662497614514]

In [42]:
a = adfuller(chuppe)
a

(-1.5002890248742013,
 0.5333683575948013,
 6,
 16,
 {'1%': -3.9240193847656246, '5%': -3.0684982031250003, '10%': -2.67389265625},
 -87.4871324427775)

In [35]:
if(a[1]>=0.05):
    print("Since the p-value is not less than .05, we fail to reject the null hypothesis. This means the time series is non-stationary. In other words, it has some time-dependent structure and does not have constant variance over time.")
else:
    print("Since the p-value is less than .05, we accept the null hypothesis. This means the time series is stationary. In other words, it doesn't have some time-dependent structure and does not have constant variance over time.")

Since the p-value is not less than .05, we fail to reject the null hypothesis. This means the time series is non-stationary. In other words, it has some time-dependent structure and does not have constant variance over time.